name: import-labels

on:
    push:
        branches: [master]
        paths:
            - ".github/labels.yml"

jobs:
    labels:
        name: Edit label

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js

              uses: actions/setup-node@v2

              with:
                  node-version: ${{ secrets.NODE_VERSION }}

            - name: Import Labels

              uses: micnncim/action-label-syncer@v1

              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
