name: "test-every-push"

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        name: Test lint, test

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js

              uses: actions/setup-node@v2

              with:
                  node-version: ${{ secrets.NODE_VERSION }}

            - name: Cache node modules

              uses: actions/cache@v2

              id: cache

              with:
                  path: node_modules
                  key: npm-packages-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'

              run: npm install

            - run: npm run lint
              if: ${{ always() }}

            - run: npm run test
              if: ${{ always() }}

            - name: Slack Notification When Failed

              if: ${{ failure() && github.event_name == 'push' && github.repository == 'jaehyuenjung/sungkyulin' }}

              uses: rtCamp/action-slack-notify@v2

              env:
                  SLACK_COLOR: "#DC2626"
                  SLACK_ICON: ${{ secrets.SLACK_ICON }}
                  SLACK_MESSAGE: test job fail
                  SLACK_TITLE: Message
                  SLACK_USERNAME: Sungkyulin Bot
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

            - name: Slack Notification If Completed

              if: ${{ success() && github.event_name == 'push' && github.repository == 'jaehyuenjung/sungkyulin' }}

              uses: rtCamp/action-slack-notify@v2

              env:
                  SLACK_COLOR: "#22C55E"
                  SLACK_ICON: ${{ secrets.SLACK_ICON }}
                  SLACK_MESSAGE: test job success
                  SLACK_TITLE: Message
                  SLACK_USERNAME: Sungkyulin Bot
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
